### PR TITLE
updated normalize-url dependency 

### PR DESCRIPTION
**Pull request by andreainnocenti**
fixing https://github.com/IonicaBizau/parse-url/issues/19

### CODE REVIEW

**Comment by Flavyoo** [comment]
@IonicaBizau Any updates on this?

**Comment by gera2ld** [comment]
This PR breaks Safari because normalize-url@6 includes regular expressions that cannot be parsed by Safari. Maybe it's worth a major release?

**Comment by OrkoHunter** [comment]
Hey sorry! This is causing errors in the browser for us at https://github.com/backstage/backstage/issues/6039. The library recommends using the `4.x` version for supporting browsers!

https://github.com/sindresorhus/normalize-url#install

**Comment by IonicaBizau** [comment]
@OrkoHunter I could try to release another patch downgrading the version and then a major release to upgrade it back. Would that work? Sorry for the late reply... I was sick last week. 🤧

**Comment by OrkoHunter** [comment]
That definitely works! @IonicaBizau And hey, no worries ❤️

**Pull request merged**
